version: '3.8'
services:
  web:
    image: nginx
    privileged: true
    network_mode: host
    environment:
      - DATABASE_PASSWORD=mysecret123
      - API_KEY=abcdef
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data:rw
  
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD=admin123
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis

volumes:
  db_data:
